export const products = [
  {
    id: 1,
    name: "Egg Chicken Red",
    unit: "4pcs",
    price: 1.99,
    category: "Eggs",
    brand: "Farm Fresh",
    image: require("./assets/egg.png"),       
  },
  {
    id: 2,
    name: "Egg Chicken White",
    unit: "180g",
    price: 1.50,
    category: "Eggs",
    brand: "Farm Fresh",
    image: require("./assets/egg_white.png"),         
  },
  {
    id: 3,
    name: "Egg Pasta",
    unit: "30gm",
    price: 15.99,
    category: "Noodles & Pasta",
    brand: "Italian",
    image: require("./assets/egg_pasta.png"),       
  },
  {
    id: 4,
    name: "Egg Noodles",
    unit: "2L",
    price: 15.99,
    category: "Noodles & Pasta",
    brand: "Ifad",
    image: require("./assets/egg-noodle.png"),          
  },
  {
    id: 5,
    name: "Mayonnais Eggless",
    unit: "1kg",
    price: 1.99,
    category: "Fast Food",
    brand: "Kazi Farmas",
    image: require("./assets/mayo.png"),          
  },
  {
    id: 6,
    name: "Egg Noodles",
    unit: "2L",
    price: 15.99,
    category: "Noodles & Pasta",
    brand: "Ifad",
    image: require("./assets/egg_noodles.png"),
  },
  {
    id: 7,
    name: "Organic Bananas",
    unit: "7pcs",
    price: 4.99,
    category: "Fruits",
    brand: "Fresh Farm",
    image: require("./assets/banana.png"),
  },
  {
    id: 8,
    name: "Red Apple",
    unit: "1kg",
    price: 4.99,
    category: "Fruits",
    brand: "Fresh Farm",
    image: require("./assets/apple.png"),
  },
  {
    id: 9,
    name: "Bell Pepper Red",
    unit: "1kg",
    price: 4.99,
    category: "Vegetables",
    brand: "Local Farm",
    image: require("./assets/pepper.png"),
  },
  {
    id: 10,
    name: "Ginger",
    unit: "250g",
    price: 2.99,
    category: "Vegetables",
    brand: "Local Farm",
    image: require("./assets/ginger.png"),
  },
  {
    id: 11,
    name: "Beef Bone",
    unit: "1kg",
    price: 4.99,
    category: "Meat & Fish",
    brand: "Organic Meat",
    image: require("./assets/beef.png"),
  },
  {
    id: 12,
    name: "Broiler Chicken",
    unit: "1kg",
    price: 4.99,
    category: "Meat & Fish",
    brand: "Organic Meat",
    image: require("./assets/chicken.png"),
  },
  {
    id: 13,
    name: "Diet Coke",
    unit: "355ml",
    price: 1.99,
    category: "Beverages",
    brand: "Coca Cola",
    image: require("./assets/diet_coke.png"),
  },
  {
    id: 14,
    name: "Sprite Can",
    unit: "325ml",
    price: 1.50,
    category: "Beverages",
    brand: "Individual Collection",
    image: require("./assets/sprite.png"),
  },
  {
    id: 15,
    name: "Apple & Grape Juice",
    unit: "2l",
    price: 15.99,
    category: "Beverages",
    brand: "Individual Collection",
    image: require("./assets/apple_juice.png"),
  },
  {
    id: 16,
    name: "Orange Juice",
    unit: "2l",
    price: 15.99,
    category: "Beverages",
    brand: "Individual Collection",
    image: require("./assets/orange_juice.png"),
  },
  {
    id: 17,
    name: "Coca Cola Can",
    unit: "325ml",
    price: 4.99,
    category: "Beverages",
    brand: "Coca Cola",
    image: require("./assets/coca_cola.png"),
  },
  {
    id: 18,
    name: "Pepsi Can",
    unit: "330ml",
    price: 4.99,
    category: "Beverages",
    brand: "Ifad",
    image: require("./assets/pepsi.png"),
  },
  {
    id: 19,
    name: "Rice",
    unit: "1kg",
    price: 2.99,
    category: "Noodles & Pasta",
    brand: "Kazi Farmas",
    image: require("./assets/Rice.png"),
  },
];

export const categories = [
  "Eggs",
  "Noodles & Pasta",
  "Chips & Crisps",
  "Fast Food",
];

export const brands = [
  "Individual Collection",
  "Coca Cola",
  "Ifad",
  "Kazi Farmas",
];